Repository datactivist/dataoutai, pull requests merged in 2021-12, with the labels that each got.

#2 API fetch method
  api/__init__.py
  api/api.py
Labels: enhancement

#3 Datasud fetcher
  README.md
  api/DataSud.py
  api/__init__.py
  api/api.py
  tools/__init__.py
  tools/tools.py
Labels: enhancement

#4 Fetching for Opendatasoft datasets
  README.md
  api/Opendatasoft.py
Labels: enhancement

#6 Data gouv fetcher
  README.md
  api/__init__.py
  api/data_gouv.py
Labels: enhancement

#7 Refacto fetchers
  README.md
  api/Opendatasoft.py
  api/__init__.py
  api/data_gouv.py
Labels: enhancement

#9 Tool function for xml cleaning
  api/Opendatasoft.py
  api/data_gouv.py
  tools/__init__.py
  tools/tools.py
Labels: refactor

#10 Datasud columns and cleanup
  api/DataSud.py
  api/Opendatasoft.py
  api/__init__.py
Labels: enhancement, refactor

#11 Opendatasoft fixes
  api/Opendatasoft.py
Labels: enhancement, bug fix

#14 Fetching script
  fetch_data.py
Labels: enhancement

#12 Added missing fields and minor fixes
  api/DataSud.py
Labels: enhancement, bug fix

#15 Fixed opendatasoft json keys and frequency check
  api/Opendatasoft.py
Labels: bug fix

#16 Added baseline LSA comparison
  models/baseline/baseline_LSA.py
Labels: enhancement

#17 Filled "columns" field and added other fields
  api/data_gouv.py
Labels: enhancement

#18 Baseline visualizer
  api/Opendatasoft.py
  visualization/visualization_baseline.py
Labels: enhancement
