Repository datactivist/dataoutai, pull requests merged in 2022-01, with the labels that each got.

#20 Improvement to the Tfidf baseline
  environment.yml
  models/baseline/baseline_TfidfVectorizer.py
Labels: enhancement

#21 Sbert model
  environment.yml
  models/baseline/baseline_TfidfVectorizer.py
  models/contextuals/sbert.py
  models/models_tools.py
  tools/tools.py
  visualization/visualization_baseline.py
Labels: enhancement

#26 Mising package init
  models/__init__.py
  models/baseline/__init__.py
  models/contextuals/__init__.py
  models/models_tools.py
  visualization/__init__.py
Labels: bug fix

#24 Code cleanup and refactoring and small optimisations
  api/DataSud.py
  api/Opendatasoft.py
  api/__init__.py
  api/api.py
  api/data_gouv.py
  fetch_data.py
  tools/__init__.py
  tools/tools.py
Labels: enhancement

#25 Fixed dependencies for Torch
  environment.yml
Labels: bug fix

#27 Added Jupyter to environment
  environment.yml
Labels: bug fix

#28 Evaluation
  models/__init__.py
  models/baseline/TfidfBasedBaseline.py
  models/baseline/__init__.py
  models/baseline/baseline_LSA.py
  models/baseline/baseline_TfidfVectorizer.py
  models/contextuals/sbert.py
  models/evaluation/various_evaluations.ipynb
  models/models_tools.py
Labels: enhancement

#29 Evaluation
  models/baseline/baseline_Word2Vec.py
  models/evaluation/clusters/word2vec_clusters_datasud_ac_10.pkl
  models/evaluation/clusters/word2vec_clusters_datasud_ac_15.pkl
  models/evaluation/clusters/word2vec_clusters_datasud_km_10.pkl
  models/evaluation/clusters/word2vec_clusters_datasud_km_15.pkl
  models/evaluation/various_evaluations.ipynb
Labels: enhancement, bug fix

#30 Added French GloVe baseline
  models/baseline/baseline_GloVe.py
  models/baseline/baseline_Word2Vec.py
  models/evaluation/various_evaluations.ipynb
Labels: enhancement

#32 Visualization server
  Dockerfile
  requirements.txt
  visualization/entrypoint.sh
  visualization/visualization_bokeh_server.py
Labels: enhancement
